spring:
  cache:
    type: caffeine
    cache-names: currencyRate

#  datasource:
#    url: jdbc:mysql://localhost:3306/currencyRateDb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
#    password: root
#    username: root
#    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect

  cloud:
    function:
      definition: currency-rate
    stream:
      kafka:
        binder:
          brokers: kafka:9092
      bindings:
        currency-rate-out-0:
          destination: currency-rate
          group: currency-rate-group
          contentType: application/json
server:
  port: 8080
